name: Hadolint Dockerfile Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Hadolint
      uses: docker://ghcr.io/hadolint/hadolint
      with:
        args: "Dockerfile"
